In [2]:
import pandas as pd
df = pd.read_csv('/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/citibike-tripdata.csv', sep=",")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  object
 1   stoptime                 300000 non-null  object
 2   start station id         299831 non-null  float64
 3   start station name       299831 non-null  object
 4   start station latitude   300000 non-null  float64
 5   start station longitude  300000 non-null  float64
 6   end station id           299831 non-null  float64
 7   end station name         299831 non-null  object
 8   end station latitude     300000 non-null  float64
 9   end station longitude    300000 non-null  float64
 10  bikeid                   300000 non-null  int64
 11  usertype                 300000 non-null  object
 12  birth year               300000 non-null  int64
 13  gender                   300000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 32.0+ MB

In [29]:
df['end station name'].value_counts().index[0]

'West St & Chambers St'

In [25]:
df.describe()

start_st_unic = df['start station id'].nunique()
print(start_st_unic)
print()
finish_st_unic = df['end station id'].nunique()
print(finish_st_unic)

759

765

In [40]:
df_tmp = df.drop(columns=["start station id", "end station id"]).copy()

df_tmp["age"] = 2018 - df_tmp["birth year"]

df_tmp = df_tmp.drop(columns=["birth year"])

df_tmp.head(5)

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age
0,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,MacDougal St & Washington Sq,40.732264,-73.998522,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1,38
1,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,Cadman Plaza West & Montague St,40.693830,-73.990539,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,0,49
2,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,1 Ave & E 62 St,40.761227,-73.960940,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1,43
3,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,St James Pl & Oliver St,40.713079,-73.998512,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,2,34
4,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,W 13 St & 6 Ave,40.736494,-73.997044,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1,24

In [54]:
df_tmp["starttime"] = pd.to_datetime(df_tmp["starttime"])
df_tmp["stoptime"] = pd.to_datetime(df_tmp["stoptime"])

df_tmp["trip duration"] = df_tmp["stoptime"] - df_tmp["starttime"]
df_tmp["trip duration minutes"] = df_tmp["trip duration"].dt.total_seconds() / 60

df_tmp = df_tmp.drop(columns = ["trip duration"])
# df_tmp["trip duration minutes"].value_counts().index[3]
df_tmp.loc[3, "trip duration minutes"]

np.float64(7.280616666666666)

In [55]:
df_tmp["weekend"] = df_tmp["starttime"].dt.dayofweek.apply(lambda x: 1 if x in [5, 6] else 0)

In [56]:
df_tmp["weekend"].value_counts()

weekend
0    184865
1    115135
Name: count, dtype: int64

In [58]:
import pandas as pd

df_tmp["starttime"] = pd.to_datetime(df_tmp["starttime"])

def get_time_of_day(hour):
    if 0 <= hour <= 6:
        return "night"
    elif 6 < hour <= 12:
        return "morning"
    elif 12 < hour <= 18:
        return "day"
    else:
        return "evening"

df_tmp["time_of_day"] = df_tmp["starttime"].dt.hour.apply(get_time_of_day)

day_count = df_tmp[df_tmp["time_of_day"] == "day"].shape[0]
night_count = df_tmp[df_tmp["time_of_day"] == "night"].shape[0]

answer = round(day_count / night_count)

print(answer)

9

In [60]:
import pandas as pd
student_data = [[1,15],[2,11],[3,11],[4,20]]


import pandas as pd

def createDataframe(student_data):
    df = pd.DataFrame(student_data, columns=["student_id", "age"])
    return df

   student_idи  age
0            1   15
1            2   11
2            3   11
3            4   20

In [67]:
import pandas as pd

melb_df = pd.read_csv('/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/melb_data_fe.csv')

# melb_df.head(5)

melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  object
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  object
 5   SellerG          13580 non-null  object
 6   Date             13580 non-null  object
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  object
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  object
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  int64
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  int64
 24  StreetType       13580 non-null  object
 25  Weekend          13580 non-null  int64
dtypes: float64(8), int64(10), object(8)
memory usage: 2.7+ MB

In [76]:
melb_df['Date'] = pd.to_datetime(melb_df['Date'])

melb_df["quarter"]      = melb_df["Date"].dt.quarter

melb_df[['Date', 'quarter']].head(4)


melb_df['quarter'].value_counts()

np.int32(2)

In [88]:
def make_category(melb_df):
    exclude_cols = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car']

    for col in melb_df.columns:
        if col not in exclude_cols and melb_df[col].nunique() <= 150:
            melb_df[col] = melb_df[col].astype('category')

    return melb_df

melb_df = make_category(melb_df)

# melb_df.columns.tolist()

# melb_df.dtypes.value_counts()

['Suburb',
 'Rooms',
 'Type',
 'Price',
 'Method',
 'SellerG',
 'Date',
 'Distance',
 'Postcode',
 'Bedroom',
 'Bathroom',
 'Car',
 'Landsize',
 'BuildingArea',
 'CouncilArea',
 'Lattitude',
 'Longtitude',
 'Regionname',
 'Propertycount',
 'MeanRoomsSquare',
 'AreaRatio',
 'MonthSale',
 'AgeBuilding',
 'WeekdaySale',
 'StreetType',
 'Weekend',
 'quarter']

In [85]:
type_counts = melb_df.dtypes.value_counts().reset_index()
type_counts.columns = ['dtype', 'columns_count']

type_counts

             dtype  columns_count
0          float64              8
1            int64              7
2         category              1
3         category              1
4         category              1
5         category              1
6   datetime64[ns]              1
7         category              1
8         category              1
9         category              1
10        category              1
11        category              1
12        category              1
13        category              1

In [91]:
melb_df.sort_values(by='Date', ascending=False).head(10)

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend,quarter
11144,Northcote,4,house,1955000.0,SP,McGrath,2017-12-08,5.3,3070,4,...,Northern Metropolitan,11364,12.600000,0.923664,12,47,4,St,0,4
11217,Surrey Hills,3,house,1775000.0,PI,Jellis,2017-12-08,10.2,3127,3,...,Southern Metropolitan,5457,15.750000,-0.721854,12,47,4,Rd,0,4
11206,St Kilda,4,house,1600000.0,VB,Gary,2017-12-08,5.0,3182,4,...,Southern Metropolitan,13240,16.000000,-0.586028,12,107,4,St,0,4
11207,Strathmore,7,house,2000000.0,SP,Nelson,2017-12-08,8.2,3041,7,...,Western Metropolitan,3284,20.882353,-0.262721,12,18,4,Rd,0,4
11208,Strathmore,4,house,1610000.0,S,other,2017-12-08,8.2,3041,4,...,Western Metropolitan,3284,24.909091,-0.517181,12,62,4,St,0,4
11209,Strathmore,3,house,1742000.0,S,Barry,2017-12-08,8.2,3041,3,...,Western Metropolitan,3284,15.750000,-0.693803,12,47,4,Rd,0,4
11210,Strathmore,3,house,1016000.0,S,other,2017-12-08,8.2,3041,3,...,Western Metropolitan,3284,15.750000,-0.413953,12,47,4,St,0,4
11211,Sunshine,3,house,700000.0,SP,other,2017-12-08,10.5,3020,3,...,Western Metropolitan,3755,16.250000,-0.577236,12,67,4,St,0,4
11212,Sunshine,2,house,615000.0,SP,Barry,2017-12-08,10.5,3020,2,...,Western Metropolitan,3755,18.800000,-0.632812,12,77,4,St,0,4
11213,Sunshine West,3,house,650000.0,VB,hockingstuart,2017-12-08,10.5,3020,3,...,Western Metropolitan,6763,18.000000,-0.691554,12,47,4,St,0,4

In [92]:
melb_df.sort_values(by=['Distance', 'Price']).loc[::10, ['Distance', 'Price']]

       Distance      Price
11428       0.0   387000.0
10512       0.7   600000.0
5727        1.2   485000.0
8671        1.2   595000.0
5736        1.2   740000.0
...         ...        ...
12011      38.0   680000.0
10673      38.0   810000.0
13429      38.0  1155000.0
11102      41.0   650000.0
12728      45.9   650000.0

[1358 rows x 2 columns]

In [93]:
mask1 = melb_df['AreaRatio'] < -0.8
mask2 = melb_df['Type'] == 'townhouse'
mask3 = melb_df['SellerG'] == 'McGrath'
melb_df[mask1 & mask2 & mask3].sort_values(
    by=['Date', 'AreaRatio'],
    ascending=[True, False],
    ignore_index=True
).loc[:, ['Date', 'AreaRatio']]

        Date  AreaRatio
0 2016-07-26  -0.974922
1 2016-09-24  -0.971831
2 2016-11-27  -0.953608
3 2016-12-11  -0.945946
4 2017-08-04  -0.947368
5 2017-08-04  -0.970874

In [100]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  category
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  category
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  category
 5   SellerG          13580 non-null  category
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  category
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  category
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  category
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  category
 24  StreetType       13580 non-null  category
 25  Weekend          13580 non-null  category
 26  quarter          13580 non-null  category
dtypes: category(11), datetime64[ns](1), float64(8), int64(7)
memory usage: 1.8 MB

In [101]:
# melb_df.sort_values(by=['Distance', 'Price']).loc[::10, ['Distance', 'Price']]

melb_df.sort_values(by = 'AreaRatio', ascending=False, ignore_index=True)['BuildingArea'].iloc[1558]

np.float64(126.0)

In [113]:
melb_df[
    (melb_df['Type'] == 'townhouse') &
    (melb_df['Rooms'] > 2)
].sort_values(
    by=['Rooms', 'MeanRoomsSquare',],
    ascending=[True, False],
    ignore_index=True
)['Price'].loc[18]


# melb_df[
#     (melb_df['Type'] == 'townhouse') &
#     (melb_df['Rooms'] > 2)
# ].sort_values(
#     by=['Rooms', 'Type'],
#     ascending=[True, False]
# )

np.float64(1300000.0)

In [117]:
melb_df.groupby(by='Type', as_index = False).mean(numeric_only=True)

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/4155525366.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby(by='Type', as_index = False).mean(numeric_only=True)

,Type,Rooms,Price,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,Lattitude,Longtitude,Propertycount,MeanRoomsSquare,AreaRatio,AgeBuilding
0,house,3.260874,1.242665e+06,10.979479,3104.080643,3.229336,1.613822,1.772674,617.181924,152.162553,-37.803795,144.994700,7259.025505,18.996731,-0.490031,55.669700
1,townhouse,2.837522,9.337351e+05,9.851346,3100.777379,2.814183,1.809695,1.555655,279.606822,134.649710,-37.815782,144.996489,7094.459605,18.569847,-0.094916,26.690305
2,unit,1.963871,6.051275e+05,7.607391,3110.797481,1.966523,1.183295,1.128936,477.314219,102.235863,-37.823710,144.996363,8199.280080,21.068242,0.319883,39.703016

In [119]:
melb_df.groupby('Type', as_index = False)['Price'].mean()

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/3238307236.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Type', as_index = False)['Price'].mean()

        Type         Price
0      house  1.242665e+06
1  townhouse  9.337351e+05
2       unit  6.051275e+05

In [120]:
melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/3783769093.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)

Regionname
Western Victoria              29.8
Eastern Victoria              25.2
Northern Victoria             21.8
South-Eastern Metropolitan    14.7
Eastern Metropolitan           7.8
Western Metropolitan           4.3
Southern Metropolitan          0.7
Northern Metropolitan          0.0
Name: Distance, dtype: float64

In [125]:

mark1 = (melb_df['Date'] >= '2017-05-01') & (melb_df['Date'] <= '2017-09-01')


melb_df[mark1].groupby('SellerG')['Price'].sum().sort_values()

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/612580397.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df[mark1].groupby('SellerG')['Price'].sum().sort_values()

SellerG
LITTLE             2742000.0
Cayzer             4439000.0
Burnham            4550500.0
Moonee             7328000.0
Thomson            8332000.0
Bells              8656000.0
Alexkarbon        10985000.0
McDonald          14637500.0
Rendina           15422276.0
Nick              16890000.0
Douglas           18341000.0
Buckingham        19033000.0
C21               19515000.0
Eview             19791500.0
Collins           20217000.0
Philip            22051800.0
Chisholm          23225000.0
Williams          23297000.0
Love              23365500.0
Purplebricks      23401000.0
O'Brien           23855508.0
HAR               25568000.0
Village           26473000.0
RW                29261000.0
Raine             30687700.0
Stockdale         35409800.0
Sweeney           36882750.0
Gary              39138400.0
Hodges            43231000.0
YPA               46354350.0
Miles             47582000.0
Kay               48569500.0
RT                50498000.0
Brad              55955000.0
Jas               59281600.0
Harcourts         68720250.0
McGrath           78386500.0
Greg              85621000.0
Woodards          85977500.0
Noel              88129800.0
Fletchers        108847700.0
Biggin           110429500.0
Buxton           219104000.0
Ray              249572986.0
Marshall         253957888.0
hockingstuart    282834310.0
Barry            296723050.0
other            365038432.0
Nelson           379767500.0
Jellis           414121833.0
Name: Price, dtype: float64

In [131]:
melb_df.groupby(['Rooms', 'Type'], as_index = False)['Price'].mean()

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/796983468.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby(['Rooms', 'Type'], as_index = False)['Price'].mean()

    Rooms       Type         Price
0       1      house  8.668655e+05
1       1  townhouse  5.927045e+05
2       1       unit  3.899289e+05
3       2      house  1.017238e+06
4       2  townhouse  7.101585e+05
5       2       unit  6.104905e+05
6       3      house  1.109233e+06
7       3  townhouse  9.847087e+05
8       3       unit  8.505963e+05
9       4      house  1.462283e+06
10      4  townhouse  1.217092e+06
11      4       unit  1.037476e+06
12      5      house  1.877327e+06
13      5  townhouse  1.035000e+06
14      5       unit           NaN
15      6      house  1.869508e+06
16      6  townhouse           NaN
17      6       unit  5.200000e+05
18      7      house  1.920700e+06
19      7  townhouse           NaN
20      7       unit           NaN
21      8      house  1.510286e+06
22      8  townhouse           NaN
23      8       unit  2.250000e+06
24     10      house  9.000000e+05
25     10  townhouse           NaN
26     10       unit           NaN

In [132]:
melb_df.groupby(['Rooms', 'Type'])['Price'].mean().unstack()

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/442157687.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby(['Rooms', 'Type'])['Price'].mean().unstack()

Type          house     townhouse          unit
Rooms
1      8.668655e+05  5.927045e+05  3.899289e+05
2      1.017238e+06  7.101585e+05  6.104905e+05
3      1.109233e+06  9.847087e+05  8.505963e+05
4      1.462283e+06  1.217092e+06  1.037476e+06
5      1.877327e+06  1.035000e+06           NaN
6      1.869508e+06           NaN  5.200000e+05
7      1.920700e+06           NaN           NaN
8      1.510286e+06           NaN  2.250000e+06
10     9.000000e+05           NaN           NaN

In [133]:
melb_df.pivot_table(
    values='Price',
    index='Rooms',
    columns='Type',
    fill_value=0
).round()

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/3628189379.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(

Type       house  townhouse       unit
Rooms
1       866866.0   592705.0   389929.0
2      1017238.0   710158.0   610491.0
3      1109233.0   984709.0   850596.0
4      1462283.0  1217092.0  1037476.0
5      1877327.0  1035000.0        0.0
6      1869508.0        0.0   520000.0
7      1920700.0        0.0        0.0
8      1510286.0        0.0  2250000.0
10      900000.0        0.0        0.0

In [134]:
melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/186795090.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(
/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/186795090.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(

                           median                          mean              \
Type                        house townhouse   unit        house   townhouse
Regionname
Eastern Metropolitan        674.0     233.5  203.0   717.422847  269.440678
Eastern Victoria            843.0       0.0  230.0  3108.960000    0.000000
Northern Metropolitan       459.5     134.0    0.0   619.249092  317.325733
Northern Victoria           724.0       0.0    0.0  3355.463415    0.000000
South-Eastern Metropolitan  630.5     240.0  199.0   664.306701  212.160000
Southern Metropolitan       586.0     246.0    0.0   569.643881  278.858824
Western Metropolitan        531.0     198.0   62.0   507.883406  244.560669
Western Victoria            599.5       0.0    0.0   655.500000    0.000000


Type                              unit
Regionname
Eastern Metropolitan        330.444444
Eastern Victoria            295.333333
Northern Metropolitan       495.026538
Northern Victoria             0.000000
South-Eastern Metropolitan  357.864865
Southern Metropolitan       466.380245
Western Metropolitan        557.637232
Western Victoria              0.000000

In [139]:
pivot = melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)


display(pivot)

# pivot.columns.to_list()

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/2603136458.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = melb_df.pivot_table(
/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/2603136458.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = melb_df.pivot_table(

                           median                          mean              \
Type                        house townhouse   unit        house   townhouse
Regionname
Eastern Metropolitan        674.0     233.5  203.0   717.422847  269.440678
Eastern Victoria            843.0       0.0  230.0  3108.960000    0.000000
Northern Metropolitan       459.5     134.0    0.0   619.249092  317.325733
Northern Victoria           724.0       0.0    0.0  3355.463415    0.000000
South-Eastern Metropolitan  630.5     240.0  199.0   664.306701  212.160000
Southern Metropolitan       586.0     246.0    0.0   569.643881  278.858824
Western Metropolitan        531.0     198.0   62.0   507.883406  244.560669
Western Victoria            599.5       0.0    0.0   655.500000    0.000000


Type                              unit
Regionname
Eastern Metropolitan        330.444444
Eastern Victoria            295.333333
Northern Metropolitan       495.026538
Northern Victoria             0.000000
South-Eastern Metropolitan  357.864865
Southern Metropolitan       466.380245
Western Metropolitan        557.637232
Western Victoria              0.000000

In [138]:
display(pivot['mean']['unit'])

Regionname
Eastern Metropolitan          330.444444
Eastern Victoria              295.333333
Northern Metropolitan         495.026538
Northern Victoria               0.000000
South-Eastern Metropolitan    357.864865
Southern Metropolitan         466.380245
Western Metropolitan          557.637232
Western Victoria                0.000000
Name: unit, dtype: float64

In [146]:
melb_df.pivot_table(
    values='BuildingArea',
    index='Rooms',
    columns='Type',
    aggfunc='mean',
    fill_value=0
)

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/3599433641.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(

Type        house   townhouse        unit
Rooms
1      112.000000   90.818182   86.232418
2      115.416917  122.284734  102.245785
3      133.605738  132.964702  121.813193
4      174.409842  170.841000  142.857143
5      290.470993  146.200000    0.000000
6      208.507576    0.000000  171.000000
7      254.654000    0.000000    0.000000
8      200.285714    0.000000  126.000000
10     126.000000    0.000000    0.000000

In [148]:
pivot = melb_df.pivot_table(
    values="Price",
    index="SellerG",
    columns="Type",
    aggfunc="median",
    fill_value=0
)

pivot.sort_values(by = 'unit', ascending=False)

/var/folders/ls/d6mbmny12hb59h29c1bx9rsm0000gn/T/ipykernel_77387/3540504685.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = melb_df.pivot_table(

Type               house  townhouse      unit
SellerG
Nick           2025000.0   780000.0  900000.0
Marshall       1975000.0  1408500.0  715000.0
Cayzer         1505000.0  1450000.0  707500.0
Kay            2220000.0  1365000.0  695000.0
Noel           1400500.0   990000.0  693250.0
Buxton         1323750.0  1030000.0  670000.0
Fletchers      1390000.0  1238000.0  653000.0
Chisholm       1520000.0   950000.0  640000.0
Philip         1035000.0   701000.0  636000.0
RT             1640000.0  1400000.0  630000.0
C21             836500.0   768750.0  625500.0
RW              870000.0   630500.0  625500.0
Moonee          806000.0   715000.0  622000.0
O'Brien         737504.0   430000.0  618500.0
Hodges         1500000.0  1105000.0  605500.0
Eview           760000.0   597500.0  602000.0
Woodards       1261000.0   865500.0  600000.0
Collins        1566500.0   930000.0  592000.0
Jellis         1505000.0  1052000.0  591750.0
Purplebricks    810000.0   927500.0  582500.0
Williams       1161000.0   735000.0  577000.0
hockingstuart  1055000.0   935000.0  566000.0
Alexkarbon     1036250.0   935000.0  560000.0
Miles          1090000.0   721500.0  555000.0
Buckingham      830000.0   820000.0  553000.0
Gary           1370000.0   993500.0  550000.0
Biggin         1151750.0   675000.0  548000.0
Greg           1330000.0   900000.0  547500.0
McGrath        1250000.0   810000.0  542500.0
other           901000.0   840500.0  535000.0
Nelson         1055000.0   730000.0  530000.0
HAR             695000.0        0.0  518000.0
McDonald       1242500.0        0.0  502500.0
Barry           830000.0   727500.0  502000.0
Harcourts       740000.0   653750.0  500000.0
Ray             900000.0   650000.0  497500.0
Thomson        1177000.0   500000.0  495000.0
Douglas         684000.0   500000.0  494500.0
Brad            875000.0   700000.0  465000.0
Rendina        1190000.0   750000.0  459000.0
Bells           692500.0   430500.0  457500.0
Jas             935000.0   699000.0  455000.0
Raine           745000.0   608000.0  447500.0
LITTLE          970000.0   800000.0  447000.0
YPA             596250.0   498500.0  443500.0
Love            780000.0   846000.0  440000.0
Village         973500.0   727500.0  420000.0
Stockdale       715500.0   550000.0  410000.0
Sweeney         850000.0   728000.0  381000.0
Burnham         922500.0        0.0  305000.0

In [153]:
import pandas as pd

movies = pd.read_csv('/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/movies_data/movies.csv', sep = ',')

# display(movies)
movies.describe(include='all')

              movieId        title genres
count     9742.000000         9742   9742
unique            NaN         9737    951
top               NaN  Emma (1996)  Drama
freq              NaN            2   1053
mean     42200.353623          NaN    NaN
std      52160.494854          NaN    NaN
min          1.000000          NaN    NaN
25%       3248.250000          NaN    NaN
50%       7300.000000          NaN    NaN
75%      76232.000000          NaN    NaN
max     193609.000000          NaN    NaN

In [168]:
ratings1 = pd.read_csv('/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/movies_data/ratings1.csv', sep = ',')
ratings2 = pd.read_csv('/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/movies_data/ratings2.csv', sep = ',')

# display(ratings1)
ratings2.describe(include='all')

             userId        movieId        rating
count  60836.000000   60836.000000  60836.000000
mean     451.987096   19787.945296      3.453095
std      105.695306   35291.305531      1.052532
min      274.000000       1.000000      0.500000
25%      366.000000    1225.000000      3.000000
50%      448.000000    3174.000000      3.500000
75%      555.000000    8622.000000      4.000000
max      610.000000  193609.000000      5.000000

In [155]:

ratings1['userId'].nunique()

274

In [160]:
dates = pd.read_csv('/Users/artempolyakov/Documents/Курсы/СкилФектори/IDE/Блок 1 (прочие файлы)/Pandas/Skillfactory/movies_data/dates.csv', sep = ',')

# display(ratings1)
# ratings1.describe(include='all')


# pd.to_datetime(df_parts[["year","month","day"]])
dates['date'] = pd.to_datetime(dates['date'])
dates['year'] = dates['date'].dt.year

dates.head(5)

                 date  year
0 2000-07-30 18:45:03  2000
1 2000-07-30 18:20:47  2000
2 2000-07-30 18:37:04  2000
3 2000-07-30 19:03:35  2000
4 2000-07-30 18:48:51  2000

In [166]:
pivot = dates.pivot_table(
    values="date",
    index="year",
    # columns="Type",
    aggfunc="count",
    fill_value=0
)

pivot.sort_values(by = "date", ascending=False)

       date
year
2000  10061
2017   8198
2007   7114
2016   6703
2015   6616
2018   6418
1996   6040
2005   5813
2012   4656
2008   4351
2009   4158
2006   4059
2003   4014
2001   3922
2002   3478
2004   3279
1999   2439
2010   2301
1997   1916
2011   1690
2013   1664
2014   1439
1998    507

In [170]:
ratings = pd.concat(
    [ratings1, ratings2],
    ignore_index=True
)
display(ratings)

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100832     610   166534     4.0
100833     610   168248     5.0
100834     610   168250     5.0
100835     610   168252     5.0
100836     610   170875     3.0

[100837 rows x 3 columns]

In [171]:
print('Число строк в таблице ratings: ', ratings.shape[0])
print('Число строк в таблице dates: ', dates.shape[0])
print(ratings.shape[0] == dates.shape[0])

Число строк в таблице ratings:  100837
Число строк в таблице dates:  100836
False

In [172]:
display(ratings1.tail(1))
display(ratings2.head(1))

       userId  movieId  rating
40000     274     5621     2.0

   userId  movieId  rating
0     274     5621     2.0

In [173]:
ratings = ratings.drop_duplicates(ignore_index=True)
print('Число строк в таблице ratings: ', ratings.shape[0])

Число строк в таблице ratings:  100836

In [174]:
ratings_dates = pd.concat([ratings, dates], axis=1)
display(ratings_dates.tail(7))

        userId  movieId  rating                date  year
100829     610   164179     5.0 2017-05-03 21:07:11  2017
100830     610   166528     4.0 2017-05-04 06:29:25  2017
100831     610   166534     4.0 2017-05-03 21:53:22  2017
100832     610   168248     5.0 2017-05-03 22:21:31  2017
100833     610   168250     5.0 2017-05-08 19:50:47  2017
100834     610   168252     5.0 2017-05-03 21:19:12  2017
100835     610   170875     3.0 2017-05-03 21:20:15  2017

In [175]:
joined = ratings_dates.join(
    movies.set_index('movieId'),
    on='movieId',
    how='left'
)
display(joined.head())

,userId,movieId,rating,date,year,title,genres
0,1,1,4.0,2000-07-30 18:45:03,2000,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2000,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,2000,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,2000,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,2000,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [ ]:
import pandas as pd

items_df = pd.DataFrame({
            'item_id': [417283, 849734, 132223, 573943, 19475, 3294095, 382043, 302948, 100132, 312394],
            'vendor': ['Samsung', 'LG', 'Apple', 'Apple', 'LG', 'Apple', 'Samsung', 'Samsung', 'LG', 'ZTE'],
            'stock_count': [54, 33, 122, 18, 102, 43, 77, 143, 60, 19]
        })

purchase_df = pd.DataFrame({
            'purchase_id': [101, 101, 101, 112, 121, 145, 145, 145, 145, 221],
            'item_id': [417283, 849734, 132223, 573943, 19475, 3294095, 382043, 302948, 103845, 100132],
            'price': [13900, 5330, 38200, 49990, 9890, 33000, 67500, 34500, 89900, 11400]
        })

# Введите свое решение ниже
items_df.head()
print()

   purchase_id  item_id  price
0          101   417283  13900
1          101   849734   5330
2          101   132223  38200
3          112   573943  49990
4          121    19475   9890

In [179]:
items_df.head()

   item_id   vendor  stock_count
0   417283  Samsung           54
1   849734       LG           33
2   132223    Apple          122
3   573943    Apple           18
4    19475       LG          102

In [180]:
purchase_df.head()

   purchase_id  item_id  price
0          101   417283  13900
1          101   849734   5330
2          101   132223  38200
3          112   573943  49990
4          121    19475   9890

In [186]:
merged = items_df.merge(purchase_df, on = 'item_id', how = 'inner')


income = (merged['stock_count'] * merged['price']).sum()

In [ ]:
import pandas as pd

orders = pd.DataFrame({
    'order_id':   [1,2,3,4,5,6,7,8,9,10],
    'customer':   ['Анна','Борис','Анна','Дима','Борис','Анна','Дима','Борис','Анна','Дима'],
    'category':   ['Книги','Электроника','Книги','Одежда','Электроника','Одежда','Книги','Одежда','Электроника','Книги'],
    'city':       ['Москва','СПб','Москва','Казань','СПб','Москва','Казань','СПб','Москва','Казань'],
    'amount':     [500,3200,450,1200,4500,800,600,950,2800,700],
    'quantity':   [2,1,3,2,1,1,2,3,1,2],
    'month':      ['Янв','Фев','Янв','Март','Фев','Март','Янв','Март','Фев','Март']
})

customers = pd.DataFrame({
    'customer': ['Анна','Борис','Дима','Лена'],
    'age':      [28, 35, 22, 31],
    'segment':  ['Premium','Standard','Standard','Premium']
})

In [207]:
result = (
    orders
    .groupby(['customer', 'month'])['amount']
    .sum()
    .reset_index(name='total_sales')
)

result = result[result['total_sales'] > 1000]

print(result)

  customer month  total_sales
1     Анна   Фев         2800
4    Борис   Фев         7700
5     Дима  Март         1900