In [35]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    'order_id':   [1,2,3,4,5,6,7,8,9,10,11,12],
    'customer':   ['Анна','Борис','Анна','Дима','Борис','Анна','Дима','Борис','Анна','Дима','Борис','Анна'],
    'category':   ['Книги','Электроника','Книги','Одежда','Электроника','Одежда','Книги','Одежда','Электроника','Книги','Книги','Одежда'],
    'city':       ['Москва','СПб','Москва','Казань','СПб','Москва','Казань','СПб','Москва','Казань','СПб','Москва'],
    'amount':     [500,3200,450,1200,4500,800,600,950,2800,700,np.nan,1500],
    'quantity':   [2,1,3,2,1,1,2,3,1,2,1,2],
    'month':      ['Янв','Фев','Янв','Март','Фев','Март','Янв','Март','Фев','Март','Апр','Апр']
})

customers = pd.DataFrame({
    'customer': ['Анна','Борис','Дима','Лена'],
    'age':      [28, 35, 22, 31],
    'segment':  ['Premium','Standard','Standard','Premium']
})

### Отсортируй заказы по сумме amount от большей к меньшей. Выведи топ-3.

In [36]:
orders.sort_values('amount', ascending=False).head(3)

   order_id customer     category    city  amount  quantity month
4         5    Борис  Электроника     СПб  4500.0         1   Фев
1         2    Борис  Электроника     СПб  3200.0         1   Фев
8         9     Анна  Электроника  Москва  2800.0         1   Фев

### Отсортируй по городу (по алфавиту), а внутри города — по сумме от большей к меньшей.

In [37]:
orders.sort_values(['city', 'amount'] , ascending=[True, False])

    order_id customer     category    city  amount  quantity month
3          4     Дима       Одежда  Казань  1200.0         2  Март
9         10     Дима        Книги  Казань   700.0         2  Март
6          7     Дима        Книги  Казань   600.0         2   Янв
8          9     Анна  Электроника  Москва  2800.0         1   Фев
11        12     Анна       Одежда  Москва  1500.0         2   Апр
5          6     Анна       Одежда  Москва   800.0         1  Март
0          1     Анна        Книги  Москва   500.0         2   Янв
2          3     Анна        Книги  Москва   450.0         3   Янв
4          5    Борис  Электроника     СПб  4500.0         1   Фев
1          2    Борис  Электроника     СПб  3200.0         1   Фев
7          8    Борис       Одежда     СПб   950.0         3  Март
10        11    Борис        Книги     СПб     NaN         1   Апр

### Добавь колонку price_per_unit = amount / quantity и отсортируй по ней.

In [38]:
orders['price_per_unit'] = orders['amount'] / orders['quantity']

orders.head()

,order_id,customer,category,city,amount,quantity,month,price_per_unit
0,1,Анна,Книги,Москва,500.0,2,Янв,250.0
1,2,Борис,Электроника,СПб,3200.0,1,Фев,3200.0
2,3,Анна,Книги,Москва,450.0,3,Янв,150.0
3,4,Дима,Одежда,Казань,1200.0,2,Март,600.0
4,5,Борис,Электроника,СПб,4500.0,1,Фев,4500.0

### В заказах есть NaN. Отсортируй по amount так, чтобы NaN оказались в начале списка.

In [39]:
orders.sort_values('amount', na_position='first')

,order_id,customer,category,city,amount,quantity,month,price_per_unit
10,11,Борис,Книги,СПб,NaN,1,Апр,NaN
2,3,Анна,Книги,Москва,450.0,3,Янв,150.000000
0,1,Анна,Книги,Москва,500.0,2,Янв,250.000000
6,7,Дима,Книги,Казань,600.0,2,Янв,300.000000
9,10,Дима,Книги,Казань,700.0,2,Март,350.000000
5,6,Анна,Одежда,Москва,800.0,1,Март,800.000000
7,8,Борис,Одежда,СПб,950.0,3,Март,316.666667
3,4,Дима,Одежда,Казань,1200.0,2,Март,600.000000
11,12,Анна,Одежда,Москва,1500.0,2,Апр,750.000000
8,9,Анна,Электроника,Москва,2800.0,1,Фев,2800.000000
1,2,Борис,Электроника,СПб,3200.0,1,Фев,3200.000000
4,5,Борис,Электроника,СПб,4500.0,1,Фев,4500.000000

### Отсортируй заказы по месяцам в правильном порядке: Янв → Фев → Март → Апр (не по алфавиту). Подсказка: используй Categorical.

In [40]:
orders['month'] = pd.Categorical(orders['month'], categories=['Янв','Фев','Март','Апр'], ordered=True)

orders.sort_values('month')

,order_id,customer,category,city,amount,quantity,month,price_per_unit
0,1,Анна,Книги,Москва,500.0,2,Янв,250.000000
2,3,Анна,Книги,Москва,450.0,3,Янв,150.000000
6,7,Дима,Книги,Казань,600.0,2,Янв,300.000000
1,2,Борис,Электроника,СПб,3200.0,1,Фев,3200.000000
4,5,Борис,Электроника,СПб,4500.0,1,Фев,4500.000000
8,9,Анна,Электроника,Москва,2800.0,1,Фев,2800.000000
3,4,Дима,Одежда,Казань,1200.0,2,Март,600.000000
5,6,Анна,Одежда,Москва,800.0,1,Март,800.000000
7,8,Борис,Одежда,СПб,950.0,3,Март,316.666667
9,10,Дима,Книги,Казань,700.0,2,Март,350.000000
10,11,Борис,Книги,СПб,NaN,1,Апр,NaN
11,12,Анна,Одежда,Москва,1500.0,2,Апр,750.000000

### Посчитай общую сумму продаж по каждому покупателю.

In [41]:
orders.groupby('customer')['amount'].sum().reset_index().sort_values('amount', ascending=False)

  customer  amount
1    Борис  8650.0
0     Анна  6050.0
2     Дима  2500.0

import pandas as pd
import numpy as np

orders = pd.DataFrame({
    'order_id':   [1,2,3,4,5,6,7,8,9,10,11,12],
    'customer':   ['Анна','Борис','Анна','Дима','Борис','Анна','Дима','Борис','Анна','Дима','Борис','Анна'],
    'category':   ['Книги','Электроника','Книги','Одежда','Электроника','Одежда','Книги','Одежда','Электроника','Книги','Книги','Одежда'],
    'city':       ['Москва','СПб','Москва','Казань','СПб','Москва','Казань','СПб','Москва','Казань','СПб','Москва'],
    'amount':     [500,3200,450,1200,4500,800,600,950,2800,700,np.nan,1500],
    'quantity':   [2,1,3,2,1,1,2,3,1,2,1,2],
    'month':      ['Янв','Фев','Янв','Март','Фев','Март','Янв','Март','Фев','Март','Апр','Апр']
})

customers = pd.DataFrame({
    'customer': ['Анна','Борис','Дима','Лена'],
    'age':      [28, 35, 22, 31],
    'segment':  ['Premium','Standard','Standard','Premium']
})

### Для каждой категории найди: количество заказов, среднюю сумму, максимальную сумму.

In [ ]:
orders.groupby('category').agg(
        orders_cnt = ('order_id', 'count'),
        avg_amount = ('amount', 'mean'),
        max_amount = ('amount', 'max')
    ).reset_index().sort_values('orders_cnt', ascending=False)

      category  orders_cnt  avg_amount  max_amount
0        Книги           5       562.5       700.0
1       Одежда           4      1112.5      1500.0
2  Электроника           3      3500.0      4500.0

### Сгруппируй по покупателю и месяцу, посчитай сумму. Оставь только группы, где сумма больше 1000.

In [50]:
df1 = orders.groupby(['customer', 'month'])['amount'].sum().reset_index()

df1[df1['amount'] > 1000]

  customer month  amount
1     Анна   Фев  2800.0
3     Анна   Апр  1500.0
4    Борис   Фев  7700.0
8     Дима  Март  1900.0

### Сделай агрегацию с разными функциями для разных колонок одной командой: сумма по amount и среднее по quantity для каждой категории.

In [51]:
orders.groupby('category').agg(
    amount_sum = ('amount', 'sum'),
    avg_quantity = ('quantity', 'mean')
).reset_index()

      category  amount_sum  avg_quantity
0        Книги      2250.0           2.0
1       Одежда      4450.0           2.0
2  Электроника     10500.0           1.0

### Добавь к таблице orders новую колонку share_of_customer — доля каждого заказа в общей сумме покупок этого клиента (без агрегирования датафрейма).

In [54]:
orders['total_amount'] = orders.groupby('customer')['amount'].transform('sum')
orders['share_of_customer'] = orders['amount'] / orders['total_amount']
orders.sort_values(['customer', 'share_of_customer'], ascending= [True, False])

,order_id,customer,category,city,amount,quantity,month,price_per_unit,total_amount,share_of_customer
8,9,Анна,Электроника,Москва,2800.0,1,Фев,2800.000000,6050.0,0.462810
11,12,Анна,Одежда,Москва,1500.0,2,Апр,750.000000,6050.0,0.247934
5,6,Анна,Одежда,Москва,800.0,1,Март,800.000000,6050.0,0.132231
0,1,Анна,Книги,Москва,500.0,2,Янв,250.000000,6050.0,0.082645
2,3,Анна,Книги,Москва,450.0,3,Янв,150.000000,6050.0,0.074380
4,5,Борис,Электроника,СПб,4500.0,1,Фев,4500.000000,8650.0,0.520231
1,2,Борис,Электроника,СПб,3200.0,1,Фев,3200.000000,8650.0,0.369942
7,8,Борис,Одежда,СПб,950.0,3,Март,316.666667,8650.0,0.109827
10,11,Борис,Книги,СПб,NaN,1,Апр,NaN,8650.0,NaN
3,4,Дима,Одежда,Казань,1200.0,2,Март,600.000000,2500.0,0.480000
9,10,Дима,Книги,Казань,700.0,2,Март,350.000000,2500.0,0.280000
6,7,Дима,Книги,Казань,600.0,2,Янв,300.000000,2500.0,0.240000

import pandas as pd
import numpy as np

orders = pd.DataFrame({
    'order_id':   [1,2,3,4,5,6,7,8,9,10,11,12],
    'customer':   ['Анна','Борис','Анна','Дима','Борис','Анна','Дима','Борис','Анна','Дима','Борис','Анна'],
    'category':   ['Книги','Электроника','Книги','Одежда','Электроника','Одежда','Книги','Одежда','Электроника','Книги','Книги','Одежда'],
    'city':       ['Москва','СПб','Москва','Казань','СПб','Москва','Казань','СПб','Москва','Казань','СПб','Москва'],
    'amount':     [500,3200,450,1200,4500,800,600,950,2800,700,np.nan,1500],
    'quantity':   [2,1,3,2,1,1,2,3,1,2,1,2],
    'month':      ['Янв','Фев','Янв','Март','Фев','Март','Янв','Март','Фев','Март','Апр','Апр']
})

customers = pd.DataFrame({
    'customer': ['Анна','Борис','Дима','Лена'],
    'age':      [28, 35, 22, 31],
    'segment':  ['Premium','Standard','Standard','Premium']
})

### Строки — покупатели, столбцы — категории, значения — сумма продаж.

In [55]:
pivot = pd.pivot_table(
    orders,
    values='amount',
    index='customer',
    columns='category',
    aggfunc='sum',
    fill_value=0
)

pivot

category   Книги  Одежда  Электроника
customer
Анна       950.0  2300.0       2800.0
Борис        0.0   950.0       7700.0
Дима      1300.0  1200.0          0.0

### Сделай сводную с двумя агрегатами одновременно: сумма и среднее по amount для каждого города по категориям.

In [59]:
pivot = pd.pivot_table(
    orders,
    values='amount',
    index='city',
    columns='category',
    aggfunc=['sum', 'mean'],
    fill_value=0,
    margins=True
)

pivot

             sum                                mean                      \
category   Книги  Одежда Электроника      All  Книги  Одежда Электроника
city
Казань    1300.0  1200.0         0.0   2500.0  650.0  1200.0         0.0
Москва     950.0  2300.0      2800.0   6050.0  475.0  1150.0      2800.0
СПб          0.0   950.0      7700.0   8650.0    0.0   950.0      3850.0
All       2250.0  4450.0     10500.0  17200.0  562.5  1112.5      3500.0


category          All
city
Казань     833.333333
Москва    1210.000000
СПб       2883.333333
All       1563.636364

### Сделай агрегацию с разными функциями для разных колонок одной командой: сумма по amount и среднее по quantity для каждой категории.

In [ ]:
orders_tmp = orders.groupby('category').agg(
    sum_amount = ('amount', 'sum'),
    mean_quantity = ('quantity', 'mean')
).reset_index()

orders_tmp